heremaps/msdkui-ios

- Documentation/Guides/ContributionGuide.md
This pull request adds a section on submitting pull requests to this project.
> MSDKUI-1657: Add Contribution Guide section on Pull Requests

- Rakefile
- adds MSDKUI framework scheme name variable with a correct name
- removes unused build variables
> MSDKUI-1658: Fix MSDKUI framework build from rake command

- Commons_Tests/Fixtures/WaypointEntryFixture.swift
- MSDKUI_Demo_UI_Tests/Impl/Utils/Utils.swift
- MSDKUI_Demo_UI_Tests/Impl/Views/RoutePlanner/RoutePlannerOptionsMatchers.swift
- MSDKUI_Demo_UI_Tests/Tests/RoutePlanner/Functional/RoutesAndManeuversTests.swift
Test is checking if route is recalculated after tunnel option is changed.
> MSDKUI-1647: Add UI test for applying tunnel options

- Documentation/Guides/ContributionGuide.md
- Documentation/Guides/UserGuide.md
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer.xcodeproj/project.pbxproj
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/Base.lproj/Main.storyboard
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/GuidanceViewController.swift
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/Info.plist
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/ManeuverViewController.swift
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile
- README.md
Due to the following renamings:
ManeuverDescriptionList -> ManeuverTableView
ManeuverDescriptionListDelegate -> ManeuverTableViewDelegate
GuidanceManeuverPanel -> GuidanceManeuverView
GuidanceManeuverPanelPresenter -> GuidanceManeuverMonitor
GuidanceManeuverPanelPresenterDelegate -> GuidanceManeuverMonitorDelegate
> MSDKUI-1668: Adapt primer example to MSDKUI 2.0.0

- Documentation/Guides/ContributionGuide.md
- Documentation/Guides/QuickStart.md
- Documentation/Guides/UserGuide.md
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/ViewController.swift
- Update WaypointListDelegate methods
- Update commit rules (72 chars for line)
- Other minor fixes / updates
> MSDKUI-1682: Update documentation

- Documentation/Guides_Examples/HelloMSDKUI/HelloMSDKUI/Info.plist
> ESD-476: Limit HelloMSDKUI Example App  to Portrait mode

- MSDKUI.xcodeproj/project.pbxproj
- MSDKUI_Dev/Components/Base.lproj/Main.storyboard
- MSDKUI_Dev/Components/GuidanceStreetSettingsViewController.swift
- MSDKUI_Dev/Components/GuidanceStreetViewController.swift
- MSDKUI_Dev/ComponentsCell.swift
- MSDKUI_Dev/ComponentsDataSource.swift
- MSDKUI_Dev/ComponentsViewController.swift
- MSDKUI_Dev/Extensions/ExtensionUITableView.swift
- MSDKUI_Dev/SettingsViewController.swift
This commit introduces a new View Controller, `ComponentsViewController`, and its data source. After this change 1) it's easier to add new entries to the table view, since all one needs to do is to add a new `ComponentEntry` to the data source, and 2) it's possible to filter by presentation style (intrinsic, constrained, or all).
> MSDKUI-1614: Filter Components by presentation style

- MSDKUI_Demo/RouteOverviewViewController.swift
> MSDKUI-1685: Fix displaying traffic delay info in drive navigation

- MSDKUI_Demo_UI_Tests/Impl/Views/DriveNavigation/DriveNavigationActions.swift
- MSDKUI_Demo_UI_Tests/Tests/DriveNavigation/Functional/GuidanceAndManeuversTests.swift
- MSDKUI_Demo_UI_Tests/Tests/RoutePlanner/Functional/RoutesAndManeuversTests.swift
- Refactored MSDKUI-1477 logic for greater stability
- Updated MSDKUI-140 with a screen height check
- Changed MSDKUI-575 image visbility check to a 'NotNil' check due to
not working properly with X-devices on landscape
Signed-off-by: Ants Peetsalu <43877908+ants86@users.noreply.github.com>
> MSDKUI-1544: Adapt tests for new iOS devices

- Documentation/Guides/QuickStart.md
> ESD-483: Fix TOC for the QuickStart Guide

- HEREMapsUI.podspec
Our pod name is HEREMapsUI but the framework is MSDKUI. This change reflects that.
> MSDKUI-1717: Fix podspec summary and description

- README.md
Setting absolute links for README.
> MSDKUI-1718: Fix broken links for public podspec

- Documentation/Guides/QuickStart.md
- Documentation/Guides/UserGuide.md
- Documentation/Guides_Examples/HelloMSDKUI/HelloMSDKUI.xcodeproj/project.pbxproj
- Documentation/Guides_Examples/HelloMSDKUI/Podfile
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer.xcodeproj/project.pbxproj
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile
- README.md
- CocoaPods 1.5.3 is required.
- The public podspec can be used now for the examples.
- Minor cleanup.
> MSDKUI-1723: Update platform requirements

- MSDKUI.xcodeproj/project.pbxproj
- MSDKUI.xcodeproj/xcshareddata/xcschemes/MSDKUI_Demo.xcscheme
This commit changes the Dev App's bundle ID to match a bundle ID belonging HERE's Team account.
> Rename Demo App's bundle ID

- MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift
- MSDKUI_Tests/GuidanceNextManeuverViewTests.swift
> MSDKUI-1740: Add tests for GuidanceNextMeneuverView layout margins

- .swiftlint.yml
- MSDKUI/Classes/ExtensionTimeInterval.swift
- MSDKUI/Classes/WaypointItem.swift
- MSDKUI/Classes/WaypointList.swift
- MSDKUI_Demo/GuidanceDashboardTableViewDataSource.swift
- MSDKUI_Demo/GuidanceDashboardViewController.swift
- MSDKUI_Demo/GuidanceViewController.swift
- MSDKUI_Demo/LocationBasedViewController.swift
- MSDKUI_Demo/WaypointViewController.swift
- MSDKUI_Demo_Tests/Extensions/ExtensionNMAMapViewTests.swift
- MSDKUI_Demo_UI_Tests/Impl/Utils/Utils.swift
- MSDKUI_Demo_UI_Tests/Impl/Views/DriveNavigation/DriveNavigationActions.swift
- MSDKUI_Dev/ComponentsViewController.swift
- MSDKUI_Tests/NavigationManagerDelegateDispatcherTests.swift
- Podfile
- Podfile.lock
* xct_specific_matcher
* last_where
* unused_control_flow_label
* vertical_whitespace_between_cases
* vertical_whitespace_closing_braces
> Update SwiftLint and enable new rules

- Documentation/Guides/QuickStart.md
> ESD-492: Adapt Set up as a verb/noun in guides

- MSDKUI/Classes/RouteDescriptionItem.swift
The stack view in a table view cell keeps the image artifact displayed
after rotation even if the image view itself is hidden. When debugging
the view hierarchy the artifact is not present. Removing the image
from the image view fixes the issue.
- adds KVO observer of image view's image to hold the last used image
reference
- removes image view's image reference when hiding the image view
- adds stored image view's image reference when showing the image view
> MSDKUI-1684: Fix warning icon artifact after rotations

- .swiftlint.yml
- MSDKUI/Classes/GuidanceEstimatedArrivalView.swift
- MSDKUI/Classes/GuidanceNextManeuverView.swift
- MSDKUI/Classes/GuidanceSpeedLimitView.swift
- MSDKUI/Classes/GuidanceSpeedView.swift
- MSDKUI_Demo/AboutViewController.swift
- MSDKUI_Demo/GuidanceDashboardTableViewCell.swift
- MSDKUI_Demo/GuidanceDashboardViewController.swift
- Podfile
- Podfile.lock
And enable new optional rule, [strong_iboutlet](https://github.com/realm/SwiftLint/issues/2433).
> MSDKUI-1769: Update SwiftLInt to 0.29.4

- MSDKUI/Assets/GuidanceManeuverView.xib
- MSDKUI/Classes/GuidanceManeuverView.swift
- MSDKUI_Demo/GuidanceViewController.swift
- MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift
- MSDKUI_Dev/Components/GuidanceManeuverSettingsViewController.swift
- MSDKUI_Dev/Components/GuidanceManeuverViewController.swift
- MSDKUI_Tests/GuidanceManeuverViewTests.swift
* Implement the state handling
* Implement GuidanceManeuverView's axis
* Update Dev App to reflect changes
* Refactor and add missing tests
> MSDKUI-1742 Improve GuidanceManeuverView

- Documentation/Guides/ContributionGuide.md
> ESD-287: Align table of contents for contribution guide

- MSDKUI.xcodeproj/project.pbxproj
- MSDKUI/Assets/GuidanceManeuverView.xib
- MSDKUI/Classes/GuidanceManeuverView.swift
- MSDKUI_Demo/GuidanceViewController.swift
- MSDKUI_Demo/Storyboards/DriveNavigation.storyboard
- MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift
- MSDKUI_Dev/Components/Base.lproj/Main.storyboard
- MSDKUI_Dev/Components/GuidanceManeuverSettingsViewController.swift
- MSDKUI_Dev/Components/GuidanceManeuverViewController.swift
- MSDKUI_Tests/GuidanceManeuverViewTests.swift
This commit contains changes for the tickets:
* **MSDKUI-1710**: Size not adapted after setting the values with layout constraints
* **MSDKUI-1716**: Wrong intrinsic size after returning from 'Updating' state
* **MSDKUI-1770**: Remove outer spacing
* **MSDKUI-1771**: Fix component that it behave correct if in intrinsic layout is applied
* **MSDKUI-1772**: The component should not preserve space for missing information
* **MSDKUI-1773**: Constraint layout handling update
* **MSDKUI-1774**: Change text behavior of info1 and info2
> MSDKUI-1742: Improve GuidanceManeuverView

- CONTRIBUTING.md
- Documentation/API_Reference/README.md
- Documentation/Guides/ContributionGuide.md
- Documentation/Guides/QuickStart.md
- Documentation/Guides/UserGuide.md
> ESD-485: Align chapter capitals and section headings

- MSDKUI_Demo_UI_Tests/Impl/Views/DriveNavigation/DriveNavigationActions.swift
Signed-off-by: Ants Peetsalu <43877908+ants86@users.noreply.github.com>
> MSDKUI-1832: Adapt tests to new ManeuverView design

- MSDKUI/Assets/ManeuverItemView.xib
- MSDKUI/Classes/ExtensionUIView.swift
- MSDKUI/Classes/ManeuverItemView.swift
- MSDKUI/Classes/ManeuverResource.swift
- MSDKUI/Classes/ManeuverTableView.swift
- MSDKUI_Demo_UI_Tests/Impl/Views/RouteOverView/RouteOverViewActions.swift
- MSDKUI_Dev/Components/ManeuverItemSettingsViewController.swift
- MSDKUI_Dev/Components/ManeuverItemViewController.swift
- MSDKUI_Tests/ManeuverItemViewTests.swift
- MSDKUI_Tests/ManeuverTableViewTests.swift
This commit re-implements `ManeuverItemView` and `ManeuverItemViewTests`.
> MSDKUI-1767: Implement intrinsic layout

- Commons_Tests/Mocks/GuidanceNextManeuverMonitorDelegateMock.swift
- MSDKUI/Classes/GuidanceNextManeuverMonitor.swift
- MSDKUI_Demo/GuidanceViewController.swift
- MSDKUI_Demo/Storyboards/DriveNavigation.storyboard
- MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift
- MSDKUI_Tests/GuidanceNextManeuverMonitorTests.swift
This pull request implement fixes for:
* MSDKUI-1833: Next next maneuver alignment is off.
* MSDKUI-1841: Guidance Screen shouldn't constrain Guidance Maneuver View in portrait.
> MSDKUI-1833, MSDKUI-1841: Fix Guidance Maneuver issues

- MSDKUI_Demo/Storyboards/EmptyView.xib
- MSDKUI_Demo_Tests/Views/EmptyViewTests.swift
This commit changes title and subtitle labels to support multiple lines.
> MSDKUI-1892: Fix EmptyRoom layout issues

- Commons_Tests/Fixtures/NMAGeoCoordinatesFixture.swift
- MSDKUI_Demo_UI_Tests/Impl/Core/CoreActions.swift
- MSDKUI_Demo_UI_Tests/Impl/Core/CoreMatchers.swift
- MSDKUI_Demo_UI_Tests/Impl/Utils/Constants.swift
- MSDKUI_Demo_UI_Tests/Impl/Utils/PositionDataSource.swift
- MSDKUI_Demo_UI_Tests/Impl/Utils/Positioning.swift
- MSDKUI_Demo_UI_Tests/Impl/Views/DriveNavigation/DriveNavigationActions.swift
- MSDKUI_Demo_UI_Tests/Impl/Views/Waypoints/WaypointActions.swift
- MSDKUI_Demo_UI_Tests/Tests/DriveNavigation/Functional/GuidanceAndManeuversTests.swift
- MSDKUI_Demo_UI_Tests/Tests/DriveNavigation/Integration/GuidanceIntegrationTests.swift
- MSDKUI_Demo_UI_Tests/Tests/RoutePlanner/Integration/RouteOptionsIntegrationTests.swift
- MSDKUI_Demo_UI_Tests/Tests/RoutePlanner/Integration/RoutePlannerIntegrationTests.swift
- Added functionality to use specific coordinates as destination.
- Adapted the tests.
- Minor improvements.
Signed-off-by: Ants Peetsalu <43877908+ants86@users.noreply.github.com>
> MSDKUI-1735: Add possibility to insert fixed coordinates

- MSDKUI_Demo/Storyboards/EmptyView.xib
> MSDKUI-1892: Update EmptyView distance to edges

- MSDKUI_Demo_UI_Tests/Impl/Core/CoreActions.swift
- MSDKUI_Demo_UI_Tests/Impl/Views/DriveNavigation/DriveNavigationActions.swift
- MSDKUI_Demo_UI_Tests/Impl/Views/Waypoints/WaypointActions.swift
- MSDKUI_Demo_UI_Tests/Tests/DriveNavigation/Functional/GuidanceAndManeuversTests.swift
- Updated documentation and improved naming
Signed-off-by: Ants Peetsalu <43877908+ants86@users.noreply.github.com>
> MSDKUI-1735: Update coordinates inject functionality

- Podfile
- Podfile.lock
to latest version, 3.4.3.
* **EarlGrey** already on latest version, 1.15.0
* **HEREMaps** already on latest version, 3.10.1
* **SwiftLint** already on latest version, 0.30.1
> MSDKUI-1871: Update OCMock

- Commons_Tests/Extensions/ExtensionXCTestCase.swift
- MSDKUI/Classes/GuidanceManeuverUtil.swift
- MSDKUI/Classes/ManeuverResources.swift
- MSDKUI/Classes/ManeuverTableView.swift
- MSDKUI/Classes/TruckOptionsPanel.swift
- MSDKUI/Classes/TunnelOptionsPanel.swift
- MSDKUI_Demo/EmptyView.swift
- MSDKUI_Demo_UI_Tests/Impl/Utils/Utils.swift
- MSDKUI_Demo_UI_Tests/Impl/Views/Waypoints/WaypointActions.swift
- MSDKUI_Demo_UI_Tests/Tests/DriveNavigation/Functional/GuidanceAndManeuversTests.swift
Using our rake task "tools:swiftlint_formatter"
> MSDKUI-1912: Fix code indentation

- MSDKUI/Assets/GuidanceNextManeuverView.xib
to avoid unnecessary compression.
> MSDKUI-1945: Set the separator as required (1000)

- MSDKUI/Assets/GuidanceNextManeuverView.xib
This pull request changes the layout constraint of the stack view to be flexible. Otherwise it conflicts with the image view constraint which sets the next maneuver icon size.
> MSDKUI-1946: Fix Next Maneuver icon behavior

- Documentation/Guides/ContributionGuide.md
- Documentation/Guides/QuickStart.md
- Documentation/Guides/UserGuide.md
- Documentation/Guides_Examples/HelloMSDKUI/HelloMSDKUI.xcodeproj/project.pbxproj
- Documentation/Guides_Examples/HelloMSDKUI/Podfile
- Documentation/Guides_Examples/HelloMSDKUI/Podfile.lock
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer.xcodeproj/project.pbxproj
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/Base.lproj/Main.storyboard
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/GuidanceViewController.swift
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/ManeuverViewController.swift
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile.lock
- README.md
- update required HERE SDK version
- update guides, apps and all other documents to MSDKUI 2.1.0
Signed-off-by: datasun <datasun@users.noreply.github.com>
> MSDKUI-1878: Update examples and docs to MSDKUI version 2.1.0

- Rakefile
> MSDKUI-2009: Fix bitcode for manually created framework

- MSDKUI_Demo/RouteOverviewViewController.swift
> MSDKUI-2005: Route is not centred after orientation change

- Documentation/Guides/ContributionGuide.md
- Documentation/Guides/QuickStart.md
- Documentation/Guides/UserGuide.md
- Documentation/Guides_Examples/HelloMSDKUI/Podfile
- Documentation/Guides_Examples/HelloMSDKUI/Podfile.lock
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/GuidanceViewController.swift
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile.lock
- README.md
Signed-off-by: datasun <datasun@users.noreply.github.com>
> MSDKUI-2066: Migrate example projects to use development branch

- MSDKUI.xcodeproj/project.pbxproj
- MSDKUI_Demo/LandingViewController.swift
- MSDKUI_Demo/Storyboards/About.storyboard
- MSDKUI_Demo/Storyboards/Base.lproj/Main.storyboard
- MSDKUI_Demo/Storyboards/DriveNavigation.storyboard
- MSDKUI_Demo/Storyboards/RoutePlanner.storyboard
- MSDKUI_Demo/WaypointViewController.swift
- MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift
> MSDKUI-2106: Update for iPhones X*

- MSDKUI/Classes/BooleanOptionItem.swift
- MSDKUI/Classes/MultipleChoiceOptionItem.swift
- MSDKUI/Classes/NumericOptionItem.swift
- MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift
> MSDKUI-2144: Handle deprecations & breaking changes

- Gemfile.lock
> Update rubyzip to version 1.3.0

- MSDKUI_Demo_UI_Tests/Tests/DriveNavigation/Functional/GuidanceAndManeuversTests.swift
> MSDKUI-2060: Update UI test to reduce failures

- MSDKUI_Tests/GuidanceEstimatedArrivalViewTests.swift
- MSDKUI_Tests/GuidanceManeuverViewTests.swift
- MSDKUI_Tests/GuidanceSpeedLimitViewTests.swift
- MSDKUI_Tests/GuidanceSpeedViewTests.swift
- MSDKUI_Tests/GuidanceStreetLabelTests.swift
- MSDKUI_Tests/ManeuverItemViewTests.swift
> MSDKUI-2198: Updated creation of NSKeyedUnarchiver to fix deprecation

- HEREMapsUI.podspec
- MSDKUI.xcodeproj/project.pbxproj
- MSDKUI_Demo_Tests/View Controllers/AboutTableViewDataSourceTests.swift
- MSDKUI_Tests/VersionTests.swift
- Podfile.lock
> MSDKUI-2187: Updated version number to 2.1.4

- Documentation/Guides_Examples/HelloMSDKUI/HelloMSDKUI/AppDelegate.swift
- Documentation/Guides_Examples/HelloMSDKUI/HelloMSDKUI/ViewController.swift
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/AppDelegate.swift
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/GuidanceHelper.swift
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/GuidanceViewController.swift
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/ManeuverViewController.swift
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/RouteHelper.swift
- Documentation/Guides_Examples/MSDKUIPrimer/MSDKUIPrimer/ViewController.swift
- MSDKUI_Tests/MSDKUI_Tests-Bridging-Header.h
- Rakefile
> MSDKUI-2211: Update copyright headers with 2020

- Commons/Info.plist
- Documentation/Guides/QuickStart.md
- Documentation/Guides_Examples/HelloMSDKUI/Podfile.lock
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile.lock
- Gemfile.lock
- HEREMapsUI.podspec
- MSDKUI.xcodeproj/project.pbxproj
- MSDKUI_Demo_Tests/View Controllers/AboutTableViewDataSourceTests.swift
- MSDKUI_Tests/VersionTests.swift
- Podfile.lock
Update version number to 2.1.5
> MSDKUI-2237: Update version number to 2.1.5

- CONTRIBUTING.md
- Documentation/API_Reference/Intro.md
- Documentation/Guides/ContributionGuide.md
- Documentation/Guides/QuickStart.md
- Documentation/Guides/UserGuide.md
- Documentation/Guides_Examples/HelloMSDKUI/README.md
- Documentation/Guides_Examples/MSDKUIPrimer/README.md
- README.md
> ESD-810: Update Product Names

- Documentation/API_Reference/Intro.md
- Documentation/Guides/ContributionGuide.md
- Documentation/Guides/QuickStart.md
- Documentation/Guides/UserGuide.md
- README.md
Xcode, Swift and CocoaPods versions in Docs updated.
Some Markdownlint warnings fixed.
> MSDKUI-2289: Update documentation

- Documentation/Guides/QuickStart.md
- Documentation/Guides_Examples/HelloMSDKUI/Podfile.lock
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile.lock
- HEREMapsUI.podspec
- MSDKUI.xcodeproj/project.pbxproj
- MSDKUI_Demo_Tests/View Controllers/AboutTableViewDataSourceTests.swift
- MSDKUI_Tests/VersionTests.swift
- Podfile.lock
> MSDKUI-2287: Update version number to 2.1.6

- HEREMapsUI.podspec
- MSDKUI_Demo_Tests/View Controllers/AboutTableViewDataSourceTests.swift
- Podfile.lock
- README.md
> MSDKUI-2285: Update dependencies to 3.16.3

- Documentation/Guides/ContributionGuide.md
- Documentation/Guides/QuickStart.md
- README.md
> MSDKUI-2342: Update documentation

- Documentation/Guides/QuickStart.md
- Documentation/Guides_Examples/HelloMSDKUI/Podfile.lock
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile
- Documentation/Guides_Examples/MSDKUIPrimer/Podfile.lock
- HEREMapsUI.podspec
- MSDKUI.xcodeproj/project.pbxproj
- MSDKUI_Demo_Tests/View Controllers/AboutTableViewDataSourceTests.swift
- MSDKUI_Tests/VersionTests.swift
- Podfile.lock
> MSDKUI-2340: Update version number
