MSDKUI_Demo_UI_Tests/Impl/Utils/Utils.swift
MSDKUI_Demo_UI_Tests/Impl/Views/DriveNavigation/DriveNavigationActions.swift

- Fixed by properly dismissing the permission alert
- Also reverted element wait back to medium

MSDKUI-1638: Fix UI test memory leak

---

MSDKUI/Classes/GuidanceManeuverData.swift
MSDKUI/Classes/GuidanceManeuverMonitor.swift
MSDKUI/Classes/GuidanceManeuverView.swift
MSDKUI_Tests/GuidanceManeuverDataTests.swift
MSDKUI_Tests/GuidanceManeuverMonitorTests.swift
MSDKUI_Tests/GuidanceManeuverViewTests.swift

This pull request moves the `MeasurementFormatter` from `GuidanceManeuverMonitor` to `GuidanceManeuverView` and changes the `GuidanceManeuverData` to carry a `Measurement` instead of a `String` to represent the distance to next maneuver.
With this change, the VIew Controller conforming to the `GuidanceManeuverMonitorDelegate` protocol can intercept the `GuidanceManeuverData` and update the distance `Measurement` before passing it to the `GuidanceManeuverView`. This allows developers to force any unit they might want to display on the `GuidanceManeuverView` (which, by default, displays units based on the locale).
This pull request also changes the `GuidanceManeuverData.getter:maneuverIcon` from
`String?` to `UIImage?`, leaving the `GuidanceManeuverView` more independent and reusable.

MSDKUI-1649: Refactor GuidanceManeuverView to take a measurement formatter

---

MSDKUI/Classes/GuidanceManeuverView.swift
MSDKUI_Tests/GuidanceManeuverViewTests.swift

The `GuidanceManeuverData` model contains nullable properties and, therefore, `GuidanceManeuverView` should reflect that.
Current implementation only updates the view if the values carried by `GuidanceManeuverData` are not `nil`. This creates a problem, since a new values with `nil` would keep previous view values.
This commit changes that. If a new model contains `nil`, the view will take that in consideration and reflect whatever the model has.
Signed-off-by: Otavio Cordeiro <41054361+otaviohere@users.noreply.github.com>

MSDKUI-1654: Improve GuidanceManeuverData handling

---

MSDKUI.xcodeproj/project.pbxproj
MSDKUI/Classes/GuidanceStreetLabel.swift
MSDKUI_Demo/GuidanceViewController.swift
MSDKUI_Demo/Storyboards/DriveNavigation.storyboard
MSDKUI_Demo_UI_Tests/Impl/Views/DriveNavigation/DriveNavigationActions.swift
MSDKUI_Tests/GuidanceStreetLabelTests.swift

Since GuidanceCurrentStreetLabel can be used to show any street, not only the
current one, the name of this class should not be associated with it.
The current street data is provided by GuidanceCurrentStreetNameMonitor which
keeps its name.
In GuidanceViewController the GuidanceStreetLabel is paired with
GuidanceCurrentStreetNameMonitor, thus related variable and function names
should keep existing naming.
- renames class name and swift file from GuidanceCurrentStreetLabel to
GuidanceStreetLabel
- renames class name and swift file from GuidanceCurrentStreetLabelTests to
GuidanceStreetLabelTests
- updates GuidanceStreetLabel class summary

MSDKUI-1661: Rename GuidanceCurrentStreetLabel to GuidanceStreetLabel

---

MSDKUI.xcodeproj/project.pbxproj
MSDKUI/Classes/ExtensionLocale.swift
MSDKUI/Classes/GuidanceSpeedLimitView.swift
MSDKUI/Classes/GuidanceSpeedView.swift
MSDKUI_Tests/ExtensionLocaleTests.swift

In Swift, `Locale` has a property called `.usesMetricSystem` which is a Boolean. For UK, it returns true since UK uses a mix of Imperial and Metric System. 
In Objective-C, `NSLocal` has 3 possible values for metric system, US, UK, Metric. This commit uses the Objective-C bridge to check the `NSLocale`'s measurement system.

MSDKUI-1672: Fix Speed Unit for UK

---

MSDKUI/Assets/GuidanceSpeedView.xib

Removed safe area layout guide to keep the view's content visible when
the GuidanceSpeedView is laid out of its ancestors' safe area

MSDKUI-1693: Remove safe area layout guide for GuidanceSpeedView

---

MSDKUI/Assets/GuidanceNextManeuverView.xib
MSDKUI/Classes/GuidanceNextManeuverView.swift
MSDKUI_Demo/GuidanceViewController.swift

This change removes margins added inside GuidanceNextManeuverView,
that causes displaying only empty background when no data is set.
Right now view itself does not contain margins, they need to be set
by using .layoutMargins property of view.

MSDKUI-1704: Fix GuidanceNextManeuverView "empty" state

---

MSDKUI/Assets/GuidanceNextManeuverView.xib
MSDKUI/Classes/GuidanceNextManeuverView.swift
MSDKUI_Tests/GuidanceNextManeuverViewTests.swift

When next maneuver has no icon, it should not preserve empty space,
so the text can be aligned to the left side of the view.

MSDKUI-1707: Remove icon view when not available in next maneuver view

---

Commons_Tests/Mocks/NMANavigationManagerDelegateMock.swift
HEREMapsUI.podspec
MSDKUI/Classes/NavigationManagerDelegateDispatcher.swift
MSDKUI_Demo_Tests/View Controllers/AboutTableViewDataSourceTests.swift
MSDKUI_Tests/NavigationManagerDelegateDispatcherTests.swift
Podfile.lock

- updates HEREMapsUI dependency version of HEREMaps
- updates unit test checking against integrated HEREMaps version
- updates project's cocoapods dependencies
- changes deprecated navigation manager did reroute function
to suggested replacement

MSDKUI-1729: Integrate HEREMaps 3.10

---

MSDKUI/Classes/ExtensionMeasurementFormatter.swift
MSDKUI/Classes/GuidanceNextManeuverView.swift
MSDKUI/Classes/ManeuverItemView.swift
MSDKUI/Classes/RouteDescriptionItem.swift
MSDKUI/Classes/RouteDescriptionItemHandler.swift
MSDKUI_Tests/GuidanceNextManeuverViewTests.swift
MSDKUI_Tests/ManeuverItemViewTests.swift

- adds long distance string formatting for use with accessibility labels
- adds long format length for route description item handler for use with accessibility labels

MSDKUI-1690: Fix VoiceOver reads feet and yards incorrectly

---

MSDKUI/Assets/GuidanceNextManeuverView.xib
MSDKUI/Classes/GuidanceNextManeuverView.swift
MSDKUI_Tests/GuidanceNextManeuverViewTests.swift

- changes the view hierarchy by removing container view
of maneuver image view
- changes the maneuver image view height constraint handling
to work with stack view's automatic height constraint application
when the arranged subview is hidden
- adds a width equal to its height constraint for maneuver image view
to react to different height constraints
- updates unit tests for the new maneuver image view handling

MSDKUI-1766: Align GuidanceNextManeuverView background size with content

---

MSDKUI/Assets/GuidanceNextManeuverView.xib
MSDKUI/Classes/GuidanceNextManeuverView.swift

Installs the constraint when loading from nib and configures maneuver
image view visibility at set up. This keeps the height constraint
between rotations.

MSDKUI-1766: Fix maneuver image size after rotation

---

MSDKUI/Assets/GuidanceNextManeuverView.xib
MSDKUI/Classes/GuidanceNextManeuverView.swift
MSDKUI_Demo/GuidanceViewController.swift
MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift
MSDKUI_Dev/Components/GuidanceNextManeuverSettingsViewController.swift
MSDKUI_Dev/Components/GuidanceNextManeuverViewController.swift
MSDKUI_Tests/GuidanceNextManeuverViewTests.swift

* Remove text alignment
* Remove inset from component. Margins should be added by developers around the component (if needed).
* Adapt the size based on the content
* Hide separator (dot) in case street or address is missing

MSDKUI-1706: Refactor GuidanceNextManeuverView

---

MSDKUI_Demo/Storyboards/DriveNavigation.storyboard

The maneuver view and next maneuver view float on top of the map and for this reason they don't need a height constraint anymore to enforce the map height. This commit removes the maneuver view height constraint.

MSDKUI-1841: Fix layout issue with initial state

---

MSDKUI/Assets/RouteDescriptionItem.xib
MSDKUI/Classes/RouteDescriptionItem.swift
MSDKUI_Tests/RouteDescriptionItemTests.swift

Originally, `RouteDescriptionItem` had an icon by default. With this commit, `RouteDescriptionItem` checks if the icon is required  before showing it.

MSDKUI-1684: Fix warning icon after device orientation

---

MSDKUI_Demo/GuidanceViewController.swift
MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift

As discussed during our workshop, we decided to keep the component behavior and handle at app level. In our app we decided to hide the distance label when distance to next maneuver is 0.

MSDKUI-1904: Improve distance to next maneuver inside roundabouts

---

MSDKUI/Classes/GuidanceManeuverMonitor.swift
MSDKUI_Demo/GuidanceViewController.swift
MSDKUI_Demo_Tests/View Controllers/GuidanceViewControllerTests.swift
MSDKUI_Tests/GuidanceManeuverMonitorTests.swift

It's up to the apps to decide if voice guidance should be enabled or disabled.

MSDKUI-1911: Move guidance voice logic to Demo app

---

MSDKUI/Assets/GuidanceNextManeuverView.xib

Uses a different constraint for the image width. Instead of setting the width size as 1:1 to height, this fix hardcodes the width to the correct value.

MSDKUI-1934: Fix image width in GuidanceNextManeuverView

---

MSDKUI_Demo/Storyboards/RoutePlanner.storyboard

The demo app should not hardcode the height of the table view cells, since they might have different heights (based on their content). This change makes the table view to use automatic height.

MSDKUI-1950: Change default row to automatic

---

MSDKUI_Dev/Components/Base.lproj/Main.storyboard

This commit changes the SpeedLimitView layout constraints to have a 50-point margin around it, like other views in the demo app.

MSDKUI-1942: Align constrained views

---

Documentation/Guides_Examples/HelloMSDKUI/Podfile.lock
Documentation/Guides_Examples/MSDKUIPrimer/Podfile.lock

This PR uses the correct CocoaPods version (as specified via `Gemfile`) to install the pods (using `bundle exec pod install` instead of `pod install`) and removes local references (as it uses the public podspec rather than the local one).

MSDKUI-1961: Update Podfile.lock for example apps

---

MSDKUI/Classes/ExtensionMeasurementFormatter.swift
MSDKUI/Classes/ExtensionNumberFormatter.swift
MSDKUI/Classes/GuidanceSpeedLimitView.swift
MSDKUI/Classes/GuidanceSpeedView.swift
MSDKUI_Tests/ExtensionNumberFormatterTests.swift
MSDKUI_Tests/GuidanceSpeedLimitViewTests.swift
MSDKUI_Tests/GuidanceSpeedViewTests.swift

Speed limit formatter replaced with the one with NumberFormatter.RoundingMode.halfUp rounding method - same as in Android.

FIXED: Speed limit is not accurate in HEREMap UI
